#:kivy 2.0.0
#:import BackGround1 backgrounds.background1
#:import FrameBase figures.framebase
#:import HangManFig3 figures.hangmanfig3

<WinScreen>:
    name: '_win_screen_'
    BackGround1:
    RelativeLayout:
        id: animation_area
        size_hint_x: 0.7
        HangManFig3:

        CustomButton:
            text: 'Back'
            icon: "skip-previous"
            pos_hint: {'x': 0, 'y': 0}
            on_release:
                root.win_popup()

