<Frame>:
	canvas.before:
		PushMatrix:
		Scale:
			x: self.width / self.w
			y: self.height / self.h

	canvas:
		Line:
			points: (150, 100, 150, 700)
			width: 20
			cap: 'square'
		Line: 
			points: (150, 700, 600, 700)
			width: 20
			cap: 'square'
		Line: 
			points: (150, 600, 250, 700)
			width: 20
		Line:
			points: (50, 80, 250, 80)
			width: 20
			cap: 'square'

	canvas.after:
		PopMatrix:
